---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cj-sample-c
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: cj-sample-i:latest
            name: cj-sample-c
            imagePullPolicy: IfNotPresent # Never # IfNotPresent
          restartPolicy: OnFailure
  
  schedule: '*/2 * * * *'
  successfulJobsHistoryLimit: 2 # retained pods
  failedJobsHistoryLimit: 2 # retained pods
