---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  creationTimestamp: null
  name: cj-sample-c
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: cj-sample-c
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - image: cj-sample-i:latest
            name: cj-sample-c
            imagePullPolicy: IfNotPresent # Never # IfNotPresent
          restartPolicy: OnFailure
  
  schedule: '*/2 * * * *'
  successfulJobsHistoryLimit: 2 # retained pods
  failedJobsHistoryLimit: 2 # retained pods
status: {}